from django.conf.urls import patterns, include, url
from django.contrib import admin
from onadata.apps.hhp_module import views

urlpatterns = patterns('',
                       url(r'^householdprofile/$', views.householdprofile, name='householdprofile'),
                       url(r'^getDistricts/$', views.getDistricts, name='getDistricts'),
                       url(r'^getUsers/$', views.getUsers, name='getUsers'),
                       url(r'^getDistrictsCharts/$', views.getDistrictsCharts, name='getDistrictsCharts'),
                       url(r'^getUsersCharts/$', views.getUsersCharts, name='getUsersCharts'),
                       url(r'^getIndividualUsersData/$', views.getIndividualUsersData, name='getIndividualUsersData'),

                       url(r'^householdprofile2/$', views.householdprofile2, name='householdprofile2'),
                       url(r'^getDistrictsHP2/$', views.getDistrictsHP2, name='getDistrictsHP2'),
                       url(r'^getUsersHP2/$', views.getUsersHP2, name='getUsersHP2'),
                       url(r'^getDistrictsChartsHP2/$', views.getDistrictsChartsHP2, name='getDistrictsChartsHP2'),
                       url(r'^getUsersChartsHP2/$', views.getUsersChartsHP2, name='getUsersChartsHP2'),
                       url(r'^getIndividualUsersDataHP2/$', views.getIndividualUsersDataHP2,name='getIndividualUsersDataHP2'),

                        url(r'^householdprofile3/$', views.householdprofile3, name='householdprofile3'),
                        url(r'^getDistrictsChartsHP3/$', views.getDistrictsChartsHP3, name='getDistrictsChartsHP3'),
                        url(r'^getUsersChartsHP3/$', views.getUsersChartsHP3, name='getUsersChartsHP3'),
                        url(r'^getIndividualUsersDataHP3/$', views.getIndividualUsersDataHP3,name='getIndividualUsersDataHP3'),

                        url(r'^birth_registration/$', views.birthregistration, name='birthregistration'),
                        url(r'^getDistrictsBR/$', views.getDistrictsBR, name='getDistrictsBR'),
                        url(r'^getUsersBR/$', views.getUsersBR, name='getUsersBR'),
                        url(r'^getDistrictsChartsBR/$', views.getDistrictsChartsBR, name='getDistrictsChartsBR'),
                        url(r'^getUsersChartsBR/$', views.getUsersChartsBR, name='getUsersChartsBR'),
                        url(r'^getIndividualUsersDataBR/$', views.getIndividualUsersDataBR, name='getIndividualUsersDataBR'),

                        url(r'^nutrition1/$', views.nutrition1, name='nutrition1'),
                        url(r'^getDistrictsNT1/$', views.getDistrictsNT1, name='getDistrictsNT1'),
                        url(r'^getUsersNT1/$', views.getUsersNT1, name='getUsersNT1'),
                        url(r'^getDistrictsChartsNT1/$', views.getDistrictsChartsNT1, name='getDistrictsChartsNT1'),
                        url(r'^getUsersChartsNT1/$', views.getUsersChartsNT1, name='getUsersChartsNT1'),
                        url(r'^getIndividualUsersDataNT1/$', views.getIndividualUsersDataNT1, name='getIndividualUsersDataNT1'),
                        url(r'^nutrition2/$', views.nutrition2, name='nutrition2'),
                        url(r'^getDistrictsNT2/$', views.getDistrictsNT2, name='getDistrictsNT2'),
                        url(r'^getUsersNT2/$', views.getUsersNT2, name='getUsersNT2'),
                        url(r'^getDistrictsChartsNT2/$', views.getDistrictsChartsNT2, name='getDistrictsChartsNT2'),
                        url(r'^getUsersChartsNT2/$', views.getUsersChartsNT2, name='getUsersChartsNT2'),
                        url(r'^getIndividualUsersDataNT2/$', views.getIndividualUsersDataNT2, name='getIndividualUsersDataNT2'),
                        url(r'^nutrition3/$', views.nutrition3, name='nutrition3'),
                        url(r'^getDistrictsNT3/$', views.getDistrictsNT3, name='getDistrictsNT3'),
                        url(r'^getUsersNT3/$', views.getUsersNT3, name='getUsersNT3'),
                        url(r'^getDistrictsChartsNT3/$', views.getDistrictsChartsNT3, name='getDistrictsChartsNT3'),
                        url(r'^getUsersChartsNT3/$', views.getUsersChartsNT3, name='getUsersChartsNT3'),
                        url(r'^getIndividualUsersDataNT3/$', views.getIndividualUsersDataNT3, name='getIndividualUsersDataNT3'),
                        url(r'^nutrition4/$', views.nutrition4, name='nutrition4'),
                        url(r'^getDistrictsNT4/$', views.getDistrictsNT4, name='getDistrictsNT4'),
                        url(r'^getUsersNT4/$', views.getUsersNT4, name='getUsersNT4'),
                        url(r'^getDistrictsChartsNT4/$', views.getDistrictsChartsNT4, name='getDistrictsChartsNT4'),
                        url(r'^getUsersChartsNT4/$', views.getUsersChartsNT4, name='getUsersChartsNT4'),
                        url(r'^getIndividualUsersDataNT4/$', views.getIndividualUsersDataNT4,name='getIndividualUsersDataNT4'),
                        url(r'^nutrition5/$', views.nutrition5, name='nutrition5'),
                        url(r'^getDistrictsNT5/$', views.getDistrictsNT5, name='getDistrictsNT5'),
                        url(r'^getUsersNT5/$', views.getUsersNT5, name='getUsersNT5'),
                        url(r'^getDistrictsChartsNT5/$', views.getDistrictsChartsNT5, name='getDistrictsChartsNT5'),
                        url(r'^getUsersChartsNT5/$', views.getUsersChartsNT5, name='getUsersChartsNT5'),
                        url(r'^getIndividualUsersDataNT5/$', views.getIndividualUsersDataNT5,name='getIndividualUsersDataNT5'),

                        url(r'^education1/$', views.education1, name='education1'),
                        url(r'^getDistrictsED1/$', views.getDistrictsED1, name='getDistrictsED1'),
                        url(r'^getUsersED1/$', views.getUsersED1, name='getUsersED1'),
                        url(r'^getDistrictsChartsED1/$', views.getDistrictsChartsED1, name='getDistrictsChartsED1'),
                        url(r'^getUsersChartsED1/$', views.getUsersChartsED1, name='getUsersChartsED1'),
                        url(r'^getIndividualUsersDataED1/$', views.getIndividualUsersDataED1,name='getIndividualUsersDataED1'),
                        url(r'^education2/$', views.education2, name='education2'),
                        url(r'^getDistrictsED2/$', views.getDistrictsED2, name='getDistrictsED2'),
                        url(r'^getUsersED2/$', views.getUsersED2, name='getUsersED2'),
                        url(r'^getDistrictsChartsED2/$', views.getDistrictsChartsED2, name='getDistrictsChartsED2'),
                        url(r'^getUsersChartsED2/$', views.getUsersChartsED2, name='getUsersChartsED2'),
                        url(r'^getIndividualUsersDataED2/$', views.getIndividualUsersDataED2,name='getIndividualUsersDataED2'),

                        url(r'^health1/$', views.health1, name='health1'),
                        url(r'^getDistrictsHL1/$', views.getDistrictsHL1, name='getDistrictsHL1'),
                        url(r'^getUsersHL1/$', views.getUsersHL1, name='getUsersHL1'),
                        url(r'^getDistrictsChartsHL1/$', views.getDistrictsChartsHL1, name='getDistrictsChartsHL1'),
                        url(r'^getUsersChartsHL1/$', views.getUsersChartsHL1, name='getUsersChartsHL1'),
                        url(r'^getIndividualUsersDataHL1/$', views.getIndividualUsersDataHL1,name='getIndividualUsersDataHL1'),
                        url(r'^health2/$', views.health2, name='health2'),
                        url(r'^getDistrictsHL2/$', views.getDistrictsHL2, name='getDistrictsHL2'),
                        url(r'^getUsersHL2/$', views.getUsersHL2, name='getUsersHL2'),
                        url(r'^getDistrictsChartsHL2/$', views.getDistrictsChartsHL2, name='getDistrictsChartsHL2'),
                        url(r'^getUsersChartsHL2/$', views.getUsersChartsHL2, name='getUsersChartsHL2'),
                        url(r'^getIndividualUsersDataHL2/$', views.getIndividualUsersDataHL2,name='getIndividualUsersDataHL2'),

                        url(r'^hiv_aids/$', views.hiv_aids, name='hiv_aids'),
                        url(r'^getDistrictsHA/$', views.getDistrictsHA, name='getDistrictsHA'),
                        url(r'^getUsersHA/$', views.getUsersHA, name='getUsersHA'),
                        url(r'^getDistrictsChartsHA/$', views.getDistrictsChartsHA, name='getDistrictsChartsHA'),
                        url(r'^getUsersChartsHA/$', views.getUsersChartsHA, name='getUsersChartsHA'),
                        url(r'^getIndividualUsersDataHA/$', views.getIndividualUsersDataHA,name='getIndividualUsersDataHA'),

                        url(r'^child_marriage/$', views.child_marriage, name='child_marriage'),
                        url(r'^getDistrictsCM/$', views.getDistrictsCM, name='getDistrictsCM'),
                        url(r'^getUsersCM/$', views.getUsersCM, name='getUsersCM'),
                        url(r'^getDistrictsChartsCM/$', views.getDistrictsChartsCM, name='getDistrictsChartsCM'),
                        url(r'^getUsersChartsCM/$', views.getUsersChartsCM, name='getUsersChartsCM'),
                        url(r'^getIndividualUsersDataCM/$', views.getIndividualUsersDataCM,name='getIndividualUsersDataCM'),

                        url(r'^wash/$', views.wash, name='wash'),
                        url(r'^getDistrictsWH/$', views.getDistrictsWH, name='getDistrictsWH'),
                        url(r'^getUsersWH/$', views.getUsersWH, name='getUsersWH'),
                        url(r'^getDistrictsChartsWH/$', views.getDistrictsChartsWH, name='getDistrictsChartsWH'),
                        url(r'^getUsersChartsWH/$', views.getUsersChartsWH, name='getUsersChartsWH'),
                        url(r'^getIndividualUsersDataWH/$', views.getIndividualUsersDataWH,name='getIndividualUsersDataWH'),

url(r'^home_page_csvp/$', views.home_page_csvp,name='home_page_csvp'),


url(r'^weather_forecast/$', views.weather_forecast, name='weather_forecast'),
                       )
